### ISSUE TITLE
issue to store images

### ISSUE THREAD

**Issue by ecpantalone** [pscedu/psc-wpdocs#1]
![image](https://user-images.githubusercontent.com/30911386/113435623-3275af80-93b1-11eb-9170-1473665cf8ea.png)

**Comment by debnigra** [comment]
![deems-square](https://user-images.githubusercontent.com/3306741/125829141-8fa8ebf5-264f-40c1-9845-c7e35d7aecc9.jpg)

**Comment by debnigra** [comment]
![image](https://user-images.githubusercontent.com/3306741/160672432-a8477326-faf0-4351-9ba4-1ddbc10bcd78.png)
