### ISSUE TITLE
Comments on the AIBD Conda_best_practices doc

### ISSUE THREAD

**Issue by meiyuw** [pscedu/psc-wpdocs#61]
1. In the section of ["create new environment"](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/conda_best_practices.md#create-new-environment) and other similar places, is it possible to give a short example ymal file?
2. The second bullet point in the ["Dos and Don't"](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/conda_best_practices.md#dos-and-donts) should be removed (just the point, not the text).

**Comment by julianx** [comment]
* Added example yaml (conda export) and txt files (conda list). 
* Removed bogus bullet point.
