### ISSUE TITLE
Comments on grapcore.md

### ISSUE THREAD

**Issue by meiyuw** [pscedu/psc-wpdocs#64]
1. Possible typo: in [Ways to run Graphcore jobs](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/grapcore.md#ways-to-run-graphcore-jobs): ...“is algo performant.”
2. In [Run jobs using the Graphcore container](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/grapcore.md#run-jobs-using-the-graphcore-container), the file name in the example is called "mnist.py," but I can only find a file called "demo.py"
3. In [Configuring tensorflow enviroment](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/grapcore.md#tensorflow), please replace "PyTorch" with TensorFlow. For example, “Then install the custom Graphcore PyTorch package via wheel file they provide (poptorch),” “Additionally, check the PyTorch installation worked by importing the library:”
4. In [mnist job on Python environment Example](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/grapcore.md#mnist-job-on-python-environment-example), I can find the file named "mnist_1_tpu.py" in the [link](https://github.com/graphcore/tutorials/tree/sdk-release-2.6/tutorials/tensorflow2/keras) provided, nor the [url](https://github.com/graphcore/tutorials/blob/sdk-release-2.6/tutorials/tensorflow2/keras/completed_demos/) shown in the example. Is "mnist_1_tpu.py" actually "completed_demo_ipu.py"?
5. Probably need to rename the file as "graphcore.md" instead of ["grapcore.md"](https://github.com/pscedu/psc-wpdocs/blob/docs/aibd/grapcore.md)?

**Comment by julianx** [comment]
1. Fixed typo.
2. Corrected the URL and file name for the py file.
3. Fixed the issues when addressing the frameworks in the similar sections
4. Corrected the URL and file name for the py file.
5. Renamed the file.
